<div id="fb-root"></div>
<div>TO DO write content</div>
<button id="login" name="login" onclick="Login()">LOGIN</button>
<button id="feed" name="feed" onclick="Feed()">FEED</button>
<button id="postGroups349541651891910" name="feed" onclick="postGroups349541651891910()">postGroups349541651891910</button>
<button id="postwall" name="postwall" onclick="postWall()">postWall</button>
<button id="getGroups" name="getGroups" onclick="getGroups()">Get Groups</button>
<button id="getSelect" name="getSelect" onclick="getSelect()">Select</button>
<button id="postPhotoGroups" name="postPhotoGroups" onclick="postPhotoGroupsSelect()">postPhotoGroups</button>
<hr/>
<form name="frmSelect">
    <input name="radion" id="rdoSelect" type="radio" value="1" onclick=" getSelect()"/><label for="rdoSelect">Check all</label>
    <input name="radion" id="rdoUnSelect" type="radio" value="0" onclick=" getSelect()"/><label for="rdoUnSelect">Un Check</label><br/>
</form>
<hr/>
<!--<form name="frmMain">-->
<div id="message">
    Logs:<br/>
</div>
<!--</form>-->
